[2024-12-05T18:38:18.579+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T18:38:18.589+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_recursion.trigger_dag_test manual__2024-12-05T18:38:14.969252+00:00 [queued]>
[2024-12-05T18:38:18.595+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_recursion.trigger_dag_test manual__2024-12-05T18:38:14.969252+00:00 [queued]>
[2024-12-05T18:38:18.595+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T18:38:18.606+0000] {taskinstance.py:2889} INFO - Executing <Task(TriggerDagRunOperator): trigger_dag_test> on 2024-12-05 18:38:14.969252+00:00
[2024-12-05T18:38:18.611+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=207) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T18:38:18.612+0000] {standard_task_runner.py:72} INFO - Started process 209 to run task
[2024-12-05T18:38:18.613+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_recursion', 'trigger_dag_test', 'manual__2024-12-05T18:38:14.969252+00:00', '--job-id', '401', '--raw', '--subdir', 'DAGS_FOLDER/test_recursion.py', '--cfg-path', '/tmp/tmpkbcsyw42']
[2024-12-05T18:38:18.614+0000] {standard_task_runner.py:105} INFO - Job 401: Subtask trigger_dag_test
[2024-12-05T18:38:18.645+0000] {task_command.py:467} INFO - Running <TaskInstance: test_recursion.trigger_dag_test manual__2024-12-05T18:38:14.969252+00:00 [running]> on host c7780884450d
[2024-12-05T18:38:18.821+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='artzsh' AIRFLOW_CTX_DAG_ID='test_recursion' AIRFLOW_CTX_TASK_ID='trigger_dag_test' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T18:38:14.969252+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T18:38:14.969252+00:00'
[2024-12-05T18:38:18.822+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T18:38:19.572+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T18:38:19.573+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_recursion, task_id=trigger_dag_test, run_id=manual__2024-12-05T18:38:14.969252+00:00, execution_date=20241205T183814, start_date=20241205T183818, end_date=20241205T183819
[2024-12-05T18:38:19.628+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T18:38:19.638+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T18:38:19.641+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
