[2024-12-05T18:38:01.853+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T18:38:01.866+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_recursion.trigger_dag_test manual__2024-12-05T18:37:58.750895+00:00 [queued]>
[2024-12-05T18:38:01.873+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_recursion.trigger_dag_test manual__2024-12-05T18:37:58.750895+00:00 [queued]>
[2024-12-05T18:38:01.874+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T18:38:01.885+0000] {taskinstance.py:2889} INFO - Executing <Task(TriggerDagRunOperator): trigger_dag_test> on 2024-12-05 18:37:58.750895+00:00
[2024-12-05T18:38:01.891+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=167) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T18:38:01.892+0000] {standard_task_runner.py:72} INFO - Started process 169 to run task
[2024-12-05T18:38:01.893+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_recursion', 'trigger_dag_test', 'manual__2024-12-05T18:37:58.750895+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/test_recursion.py', '--cfg-path', '/tmp/tmp79jb709t']
[2024-12-05T18:38:01.895+0000] {standard_task_runner.py:105} INFO - Job 391: Subtask trigger_dag_test
[2024-12-05T18:38:01.934+0000] {task_command.py:467} INFO - Running <TaskInstance: test_recursion.trigger_dag_test manual__2024-12-05T18:37:58.750895+00:00 [running]> on host c7780884450d
[2024-12-05T18:38:02.136+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='artzsh' AIRFLOW_CTX_DAG_ID='test_recursion' AIRFLOW_CTX_TASK_ID='trigger_dag_test' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T18:37:58.750895+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T18:37:58.750895+00:00'
[2024-12-05T18:38:02.137+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T18:38:02.932+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T18:38:02.933+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_recursion, task_id=trigger_dag_test, run_id=manual__2024-12-05T18:37:58.750895+00:00, execution_date=20241205T183758, start_date=20241205T183801, end_date=20241205T183802
[2024-12-05T18:38:02.989+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T18:38:03.002+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T18:38:03.011+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
